# 具体配置文档地址 https://github.com/lowlighter/metrics/blob/master/action.yml
# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference

name: GitHub metrics
on:
  schedule: 
      - cron: "* */12 * * *"
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # base metrics
      - name: base_metrics
        uses: lowlighter/metrics@latest
        with:
          filename: base_metrics.svg
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: sun0225SUN
          template: classic
          base: "header, activity, community, repositories"
          config_timezone: Asia/Shanghai
      
      # plugin metrics
      - name: plugin_metrics
        uses: lowlighter/metrics@latest
        with:
          filename: plugin_metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: sun0225SUN
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          # Achievements 我的成就
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          # Recent activity 最近活动
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 3
          plugin_activity_load: 300
          plugin_activity_visibility: all
          #  Follow-up of issues and pull requests
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_introduction: yes
          plugin_introduction_title: yes
          # Isometric commit calendar 日历图
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          # Most used languages 常用语言统计
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          # followers, following 关注与被关注
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          # projects 我的工程
          plugin_projects: yes
          plugin_projects_limit: 3
          plugin_stars: yes
          plugin_stars_limit: 3
          # Website performances 网站性能
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes                            # Print detailed audit metrics (打印详细的审计指标)
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}    # Optional but recommended ( Google's PageSpeed API)
          plugin_pagespeed_screenshot: yes                          # Display a screenshot of your website (是否显示网页截图)
          plugin_pagespeed_url: https://www.sunguoqi.com            # Website to audit (站点URL)
          
      # GitHub Skyline 3D calendar 3D贡献图
      - name: GitHub Skyline 3D calendar
        uses: lowlighter/metrics@latest
        with:
          filename: skyline_calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: sun0225SUN
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_skyline: yes
          plugin_skyline_year: 2021           # Set to 0 to display current year (统计年份)
          plugin_skyline_frames: 60          # Use 60 frames (half-loop) (半循环or全循环)
          plugin_skyline_quality: 0.5         # Set image quality (图片质量) 
          plugin_skyline_compatibility: no    # Support additional browsers (⚠️ increases file size and reduce optimization)   
