# 具体配置文档地址 https://github.com/lowlighter/metrics/blob/master/action.yml
# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference

name: GitHub metrics
on:
  schedule: 
      - cron: "* */12 * * *"
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    
#       # 仅显示 base metrics
#       - name: base_metrics
#         uses: lowlighter/metrics@latest
#         with:
#           filename: base_metrics.svg
#           # Your GitHub token
#           token: ${{ secrets.METRICS_TOKEN }}
#           # Options
#           user: sun0225SUN
#           template: classic
#           base: "header, activity, community, repositories"
#           config_timezone: Asia/Shanghai
      
#       # 各种插件  plugin metrics
#       - name: plugin_metrics
#         uses: lowlighter/metrics@latest
#         with:
#           filename: plugin_metrics.svg
#           # Your GitHub token
#           token: ${{ secrets.METRICS_TOKEN }}
#           # base 基础配置项
#           user: sun0225SUN
#           template: classic
#           base: ""
#           config_timezone: Asia/Shanghai
#           # plugin 插件配置项
#           plugin_achievements: yes
#           plugin_achievements_display: compact
#           plugin_achievements_secrets: yes
#           plugin_achievements_threshold: C
#           plugin_activity: yes
#           plugin_activity_days: 14
#           plugin_activity_filter: all
#           plugin_activity_limit: 3
#           plugin_activity_load: 300
#           plugin_activity_visibility: all
#           plugin_followup: yes
#           plugin_followup_sections: repositories
#           plugin_introduction: yes
#           plugin_introduction_title: yes
#           plugin_isocalendar: yes
#           plugin_isocalendar_duration: full-year
#           plugin_languages: yes
#           plugin_languages_analysis_timeout: 15
#           plugin_languages_categories: markup, programming
#           plugin_languages_colors: github
#           plugin_languages_limit: 8
#           plugin_languages_recent_categories: markup, programming
#           plugin_languages_recent_days: 14
#           plugin_languages_recent_load: 300
#           plugin_languages_sections: most-used
#           plugin_languages_threshold: 0%
#           plugin_people: yes
#           plugin_people_limit: 24
#           plugin_people_size: 28
#           plugin_people_types: followers, following
#           plugin_projects: yes
#           plugin_projects_limit: 3
#           plugin_stars: yes
#           plugin_stars_limit: 3
          
#       # 3D贡献图  GitHub Skyline 3D calendar
#       - name: GitHub Skyline 3D calendar
#         uses: lowlighter/metrics@latest
#         with:
#           filename: skyline_metrics.svg
#           # Your GitHub token
#           token: ${{ secrets.METRICS_TOKEN }}
#           # base 基础配置项
#           user: sun0225SUN
#           template: classic
#           base: ""
#           config_timezone: Asia/Shanghai
#           # plugin 插件配置项
#           plugin_skyline: yes
#           plugin_skyline_year: 2021           # Set to 0 to display current year
#           plugin_skyline_frames: 120          # Use 60 frames (half-loop)
#           plugin_skyline_quality: 0.1         # Set image quality   
#           plugin_skyline_compatibility: no    # Support additional browsers (⚠️ increases file size and reduce optimization)
          
      # 3D贡献图  GitHub Skyline 3D calendar
      - name: my website
        uses: lowlighter/metrics@latest
        with:
          filename: website.svg
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # base 基础配置项
          user: sun0225SUN
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          # plugin 插件配置项
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_screenshot: yes                      # Display a screenshot of your website
          plugin_pagespeed_url: https://www.sunguoqi.com        # Website to audit (defaults to your GitHub linked website)
          
