name: Social Readme

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: sun0225SUN/Social-Readme@main
        with:
          blog_rss_link: https://blog.sunguoqi.com/rss.xml
          blog_limit: 5 # blog数量
          brain_rss_link: https://brain.sunguoqi.com/rss.xml
          brain_limit: 5
          douban_name: sunguoqi
          douban_limit: 5 # 豆瓣最新动态数量
          commit_message: Updated social rss by social-readme # commit说明
          
